"""empty message

Revision ID: 64dfb13284d5
Revises: 3fedff1cb713
Create Date: 2021-01-24 08:16:05.442470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dfb13284d5'
down_revision = '3fedff1cb713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee') as batch_op:
        batch_op.add_column( sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'age')
    # ### end Alembic commands ###
