"""empty message

Revision ID: 7b1f43529736
Revises: 64dfb13284d5
Create Date: 2021-01-24 08:17:39.530088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1f43529736'
down_revision = '64dfb13284d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee') as batch_op:   
        batch_op.drop_column('email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('email', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
